lints.workspace = true

[package]
name = "progress-bar"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
indicatif = { workspace = true, optional = true }

[features]
default = []
terminal = ["indicatif"]
