# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PRAGMA.Amaru
PackageVersion: 10.11.20260925
InstallerType: wix
ReleaseDate: 2026-09-25
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/pragma-org/amaru/releases/download/v10.11.20260925/amaru-10.11.20260925-windows-x86_64.msi
    InstallerSha256: 012BDF70643C0E7ACF53501CD1B11E272F94D68F5124F87471E1961810ED499F
ManifestType: installer
ManifestVersion: 1.12.0
