# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PRAGMA.Amaru
PackageVersion: 10.11.20260730
InstallerType: wix
ReleaseDate: 2026-07-30
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/pragma-org/amaru/releases/download/v10.11.20260730/amaru-10.11.20260730-windows-x86_64.msi
    InstallerSha256: 0B4BA7613851D3A831931BBDE128E26B41C5FBD9BD094888887D50800F567CE8
ManifestType: installer
ManifestVersion: 1.12.0
