// Copyright 2026 PRAGMA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Occupancy of a lock-step protocol state relative to CIP-0164 pipelining.
//!
//! Generated by [`make_states`](crate::make_states) when `switch` (and optionally
//! `terminal`) is named. Everything else is remote agency.

/// Where a live protocol state sits relative to the pipelining switch state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Occupancy {
    /// Named switch state: initiator has agency and a new request may be sent.
    Switch,
    /// Responder has agency. The recv cursor stays until the machine re-enters switch.
    Remote,
    /// Terminal state: no agency.
    Terminal,
}

impl Occupancy {
    pub fn is_switch(self) -> bool {
        matches!(self, Self::Switch)
    }

    pub fn is_remote(self) -> bool {
        matches!(self, Self::Remote)
    }

    pub fn is_terminal(self) -> bool {
        matches!(self, Self::Terminal)
    }
}

/// Occupancy of a live protocol state (or a wrapper that holds one).
pub trait OccupancyOf {
    fn occupancy(&self) -> Occupancy;

    fn in_switch(&self) -> bool {
        self.occupancy().is_switch()
    }

    fn is_remote(&self) -> bool {
        self.occupancy().is_remote()
    }

    fn is_terminal(&self) -> bool {
        self.occupancy().is_terminal()
    }
}
