// Copyright 2026 PRAGMA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Linear handle: [`Effects`] plus a remainder type `Rem`.
//!
//! [`State::receive`] opens a [`Session`]. [`send`](Session::send) / [`send_any`](Session::send_any)
//! / [`call`](Session::call) / [`wait`](Session::wait) / [`set_timeout`](Session::set_timeout) /
//! [`clear_timeout`](Session::clear_timeout) require [`Select`] of that effect
//! ([`IntoRoleMail`](super::IntoRoleMail) at the send call site,
//! [`IntoRoleCall`](super::IntoRoleCall) at the call site);
//! [`finish`](Session::finish) requires [`CanFinish`].
//! [`convert_input`](State::convert_input) classifies a mailbox value and does
//! not consume the state token — [`receive`](State::receive) does.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt,
    future::Future,
    marker::PhantomData,
    time::Duration,
};

use super::{
    Clean, DescribeAst, FmtPar, IntoRoleCall, IntoRoleMail, Occupancy, RemainderAst, RoleTag, Select,
    effect::{Call as CallEff, ClearTimeout, Send as SendEff, SendAny, SetTimeout, Terminate, Wait},
    list::{self, CanFinish, InputName, StateName},
};
use crate::{Effects, ExternalEffectAPI, Instant, SendData, StageRef};

/// Witness that only [`initial_state`] and [`Session::finish`] may construct a protocol state.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Marker(Private);

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub(super) struct Private;

pub struct InitialState;
pub struct NotInitialState;

/// A zero-sized protocol state. Construct the initial one with [`initial_state`].
pub trait State: Sized + Send + 'static {
    const NAME: &'static str;
    /// Used by [`initial_state`] and [`Session::finish`] only.
    #[doc(hidden)]
    fn make(marker: Marker) -> Self;
    type Initial;

    /// Consume the receive allowance for `input` and return the remaining effects.
    ///
    /// `input` need not be the stage mailbox type. It is typically one variant
    /// (or a newtype of a variant) so different messages select different
    /// [`OnReceive`] impls and therefore different remainders.
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// define_role_tag!(ToPeer);
    /// on_receive!(Idle, u8 => Send<ToPeer, String> => Done);
    /// fn bad<M>(s: Idle, eff: amaru_pure_stage::Effects<M>) {
    ///     let _ = s.receive(true, eff);
    /// }
    /// ```
    fn receive<In, M>(self, input: In, eff: Effects<M>) -> Session<M, <Self as OnReceive<In>>::Then>
    where
        Self: OnReceive<In>,
    {
        <Self as OnReceive<In>>::open(self, input, eff)
    }

    /// Classify a mailbox message as an admissible input for this state.
    ///
    /// `In` is the input enum generated by [`on_receive`](crate::on_receive)
    /// (`Idle as IdleIn { ... }`). Matching `Ok` is exhaustive over legal
    /// inputs; `Err` is the dedicated inadmissible case and yields the original
    /// mailbox value. The state token is not consumed.
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
    /// struct A(u8);
    /// #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
    /// struct B(u16);
    /// define_mailbox!(Mail { A(A), B(B) });
    /// on_receive!(Idle as IdleIn { A => { Done } });
    /// fn bad(idle: Idle, msg: Mail) {
    ///     match idle.convert_input(msg) {
    ///         Ok(IdleIn::A(_)) => {}
    ///         // missing Err — must handle inadmissible input
    ///     }
    /// }
    /// ```
    fn convert_input<In, M>(&self, msg: M) -> Result<In, M>
    where
        In: ExtractInput<M>,
    {
        In::extract(msg)
    }

    fn name(&self) -> &'static str {
        Self::NAME
    }
}

/// Pull a protocol payload out of a stage mailbox value, or give the mailbox back.
pub trait FromMailbox<M>: Sized {
    fn from_mailbox(msg: M) -> Result<Self, M>;
}

impl<T> FromMailbox<T> for T {
    fn from_mailbox(msg: T) -> Result<Self, T> {
        Ok(msg)
    }
}

/// Classify a mailbox message as one of a state's admissible inputs.
pub trait ExtractInput<M>: Sized {
    fn extract(msg: M) -> Result<Self, M>;
}

/// The remainder after [`State::receive`] of `In`.
pub trait OnReceive<In>: State {
    type Then;

    fn open<M>(self, input: In, eff: Effects<M>) -> Session<M, Self::Then> {
        let _ = (self, input);
        Session::new(eff)
    }
}

/// Receive-arm remainders for a protocol state.
///
/// Generated **only** by grouped [`on_receive`](crate::on_receive), including
/// `on_receive!(Done as DoneIn {})`. Single-input `on_receive!(S, In => …)` does
/// not implement this trait.
pub trait DescribeReceives: State {
    fn describe_receives() -> BTreeMap<InputName, RemainderAst>;
}

/// Live-enum occupancy map and the first initial state.
///
/// Generated by [`make_states`](crate::make_states). [`Self::describe_states`] is empty
/// when `switch` was not named.
pub trait DescribeStates {
    /// [`State::NAME`] of the first initial state (names before `;` in `make_states!`).
    fn initial() -> StateName;

    /// Occupancy of each live-enum variant, or empty if `switch` was omitted.
    fn describe_states() -> BTreeMap<StateName, Occupancy>;
}

/// Remainder graph extracted from grouped `on_receive!` and `make_states!`.
///
/// Built by [`typestate_graph`](crate::typestate_graph) or [`Self::new`].
/// [`Session::describe`] stays diagnostic; tests should use this structure, not
/// parse those strings.
///
/// Fields stay `pub` for reads and hand-built values. [`Self::new`] derives
/// [`Self::states`] from [`Self::receives`] keys. `initial` need not be in
/// `states` (receiving-only extract).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypeGraph {
    /// Names with a remainder map; derived from [`Self::receives`] by [`Self::new`].
    pub states: BTreeSet<StateName>,
    pub initial: StateName,
    /// Empty if `make_states!` had no `switch`. Partial extract: occupancy may
    /// include names without a remainder.
    pub occupancy: BTreeMap<StateName, Occupancy>,
    pub receives: BTreeMap<StateName, BTreeMap<InputName, RemainderAst>>,
}

impl TypeGraph {
    /// Derive [`Self::states`] from `receives` keys.
    ///
    /// Occupancy is the live-enum map from [`DescribeStates`] and may mention
    /// names with no remainder (partial extract). `initial` need not be in
    /// `states`.
    pub fn new(
        initial: StateName,
        occupancy: BTreeMap<StateName, Occupancy>,
        receives: BTreeMap<StateName, BTreeMap<InputName, RemainderAst>>,
    ) -> Self {
        debug_assert!(
            occupancy.is_empty() || occupancy.contains_key(initial),
            "non-empty occupancy must include the initial state",
        );
        Self { states: receives.keys().copied().collect(), initial, occupancy, receives }
    }
}

/// Construct the unique initial state of a protocol. The only other way to
/// obtain a state value is [`Session::finish`].
pub fn initial_state<S>() -> S
where
    S: State<Initial = InitialState>,
{
    S::make(Marker(Private))
}

/// Terminator of an effect sequence: after the preceding effects, the session
/// finishes in `S`.
pub struct To<S: State>(PhantomData<S>);

/// `Effects` plus the type-level remainder of a receive.
///
/// Protocol [`send`](Self::send), [`send_any`](Self::send_any), [`call`](Self::call),
/// [`wait`](Self::wait), [`set_timeout`](Self::set_timeout),
/// [`clear_timeout`](Self::clear_timeout), and [`terminate`](Self::terminate)
/// consume from `Rem`. Local helpers (`clock`, `external`) do not.
pub struct Session<M, Rem> {
    effects: Effects<M>,
    _rem: PhantomData<fn() -> Rem>,
}

impl<M, Rem> Session<M, Rem> {
    fn new(effects: Effects<M>) -> Self {
        Self { effects, _rem: PhantomData }
    }

    /// Human-readable remainder (`Send<Role, A> => S | Send<Role, B> => T`).
    pub fn describe() -> String
    where
        Rem: FmtPar,
    {
        list::describe::<Rem>()
    }

    /// Value-level remainder. Does not parse [`Self::describe`].
    pub fn describe_ast() -> RemainderAst
    where
        Rem: DescribeAst,
    {
        list::describe_ast::<Rem>()
    }

    pub fn me(&self) -> StageRef<M>
    where
        M: SendData,
    {
        self.effects.me()
    }

    pub fn clock(&self) -> crate::BoxFuture<'static, Instant> {
        self.effects.clock()
    }

    pub fn external<T: ExternalEffectAPI>(&self, effect: T) -> crate::BoxFuture<'static, T::Response> {
        self.effects.external(effect)
    }

    /// Protocol send. Consumes a [`Send<Tag, T>`] allowance.
    ///
    /// `target` wraps a [`StageRef`] claiming `Tag`; its mailbox must implement [`From<T>`].
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// define_role_tag!(ToPeer);
    /// define_role!(Peer, ToPeer, String);
    /// on_receive!(Idle, u8 => Send<ToPeer, String> => Done);
    /// async fn bad<M>(s: Idle, target: &Peer, eff: amaru_pure_stage::Effects<M>)
    /// where
    ///     M: Send,
    /// {
    ///     let _ = s.receive(1u8, eff).send(target, 0u32).await;
    /// }
    /// ```
    ///
    /// After choosing one alternative, the other sequence is gone:
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; StateA, StateC });
    /// define_role_tag!(RoleA);
    /// define_role_tag!(RoleB);
    /// define_role_tag!(RoleC);
    /// define_role_tag!(RoleD);
    /// define_role!(DestA, RoleA, u8);
    /// define_role!(DestB, RoleB, u8);
    /// define_role!(DestC, RoleC, u8);
    /// define_role!(DestD, RoleD, u8);
    /// on_receive!(Idle, Go => Send<RoleA, u8>, Send<RoleB, u8> => StateA | Send<RoleC, u8>, Send<RoleD, u8> => StateC);
    /// struct Go;
    /// async fn after_a_cannot_send_d<M>(
    ///     s: Idle,
    ///     a: &DestA,
    ///     d: &DestD,
    ///     eff: amaru_pure_stage::Effects<M>,
    /// ) where
    ///     M: Send,
    /// {
    ///     let s = s.receive(Go, eff).send(a, 1u8).await;
    ///     let _ = s.send(d, 1u8).await;
    /// }
    /// ```
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; StateA, StateC });
    /// define_role_tag!(RoleA);
    /// define_role_tag!(RoleB);
    /// define_role_tag!(RoleC);
    /// define_role_tag!(RoleD);
    /// define_role!(DestA, RoleA, u8);
    /// define_role!(DestB, RoleB, u8);
    /// define_role!(DestC, RoleC, u8);
    /// define_role!(DestD, RoleD, u8);
    /// on_receive!(Idle, Go => Send<RoleA, u8>, Send<RoleB, u8> => StateA | Send<RoleC, u8>, Send<RoleD, u8> => StateC);
    /// struct Go;
    /// async fn after_c_cannot_send_b<M>(
    ///     s: Idle,
    ///     c: &DestC,
    ///     b: &DestB,
    ///     eff: amaru_pure_stage::Effects<M>,
    /// ) where
    ///     M: Send,
    /// {
    ///     let s = s.receive(Go, eff).send(c, 1u8).await;
    ///     let _ = s.send(b, 1u8).await;
    /// }
    /// ```
    pub fn send<Tag, T, Dest, I>(
        self,
        target: &Dest,
        msg: T,
    ) -> impl Future<Output = Session<M, After<Rem, SendEff<Tag, T>, I>>> + Send
    where
        Tag: RoleTag,
        Dest: IntoRoleMail<Tag, T>,
        Rem: Select<SendEff<Tag, T>, I>,
        Rem::Rest: Clean,
        M: Send,
    {
        let mail = target.encode(msg);
        let send = self.effects.send(target.mailbox(), mail);
        async move {
            send.await;
            Session::new(self.effects)
        }
    }

    /// Protocol call. Consumes a [`Call<Tag, T>`](super::Call) allowance.
    ///
    /// Waits for [`IntoRoleCall::Reply`](super::IntoRoleCall::Reply) or
    /// [`IntoRoleCall::TIMEOUT`](super::IntoRoleCall::TIMEOUT) (`None`). The
    /// wait is the back-pressure: the session does not continue until the
    /// callee answers (or the timer fires).
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// define_role_tag!(ToPeer);
    /// define_role!(Peer, ToPeer, String);
    /// on_receive!(Idle, u8 => Call<ToPeer, String> => Done);
    /// async fn bad<M>(s: Idle, target: &Peer, eff: amaru_pure_stage::Effects<M>)
    /// where
    ///     M: Send,
    /// {
    ///     let _ = s.receive(1u8, eff).call(target, 0u32).await;
    /// }
    /// ```
    pub fn call<Tag, T, Dest, I>(
        self,
        target: &Dest,
        msg: T,
    ) -> impl Future<Output = (Option<Dest::Reply>, Session<M, After<Rem, CallEff<Tag, T>, I>>)> + Send
    where
        Tag: RoleTag,
        Dest: IntoRoleCall<Tag, T> + Clone + Send + 'static,
        Rem: Select<CallEff<Tag, T>, I>,
        Rem::Rest: Clean,
        M: Send,
        T: Send + 'static,
    {
        let dest = target.clone();
        let mailbox = dest.mailbox().clone();
        let call = self.effects.call(&mailbox, Dest::TIMEOUT, move |reply| dest.encode(msg, reply));
        async move {
            let reply = call.await;
            (reply, Session::new(self.effects))
        }
    }

    /// Send any mailbox message to `target`. Consumes a [`SendAny<Tag>`]
    /// permission, or uses a [`Repeat<SendAny<Tag>>`](super::Repeat) without
    /// removing it.
    pub fn send_any<Tag, T, Dest, I>(
        self,
        target: &Dest,
        msg: T,
    ) -> impl Future<Output = Session<M, After<Rem, SendAny<Tag>, I>>> + Send
    where
        Tag: RoleTag,
        Dest: IntoRoleMail<Tag, T>,
        Rem: Select<SendAny<Tag>, I>,
        Rem::Rest: Clean,
        M: Send,
    {
        let mail = target.encode(msg);
        let send = self.effects.send(target.mailbox(), mail);
        async move {
            send.await;
            Session::new(self.effects)
        }
    }

    /// Protocol wait. Consumes a [`Wait`] allowance.
    pub fn wait<I>(self, delay: Duration) -> impl Future<Output = (Instant, Session<M, After<Rem, Wait, I>>)> + Send
    where
        Rem: Select<Wait, I>,
        Rem::Rest: Clean,
        M: Send,
    {
        let wait = self.effects.wait(delay);
        async move {
            let now = wait.await;
            (now, Session::new(self.effects))
        }
    }

    /// Arm a protocol timeout. Consumes a [`SetTimeout`] allowance.
    ///
    /// Uses slot 0. For pipelined instances on one stage, use
    /// [`set_timeout_at`](Self::set_timeout_at).
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// on_receive!(Idle, u8 => SetTimeout => Done);
    /// fn bad<M>(s: Idle, eff: amaru_pure_stage::Effects<M>) -> Done
    /// where
    ///     M: amaru_pure_stage::SendData,
    /// {
    ///     s.receive(1u8, eff).finish()
    /// }
    /// ```
    pub fn set_timeout<I>(
        self,
        delay: Duration,
        msg: M,
    ) -> impl Future<Output = Session<M, After<Rem, SetTimeout, I>>> + Send
    where
        Rem: Select<SetTimeout, I>,
        Rem::Rest: Clean,
        M: SendData,
    {
        self.set_timeout_at(0, delay, msg)
    }

    /// Arm a protocol timeout on `slot`. Consumes a [`SetTimeout`] allowance.
    pub fn set_timeout_at<I>(
        self,
        slot: u64,
        delay: Duration,
        msg: M,
    ) -> impl Future<Output = Session<M, After<Rem, SetTimeout, I>>> + Send
    where
        Rem: Select<SetTimeout, I>,
        Rem::Rest: Clean,
        M: SendData,
    {
        let set = self.effects.set_timeout_at(slot, delay, msg);
        async move {
            set.await;
            Session::new(self.effects)
        }
    }

    /// Cancel the protocol timeout. Consumes a [`ClearTimeout`] allowance.
    pub fn clear_timeout<I>(self) -> impl Future<Output = Session<M, After<Rem, ClearTimeout, I>>> + Send
    where
        Rem: Select<ClearTimeout, I>,
        Rem::Rest: Clean,
        M: Send,
    {
        self.clear_timeout_at(0)
    }

    /// Cancel the protocol timeout on `slot`. Consumes a [`ClearTimeout`] allowance.
    pub fn clear_timeout_at<I>(self, slot: u64) -> impl Future<Output = Session<M, After<Rem, ClearTimeout, I>>> + Send
    where
        Rem: Select<ClearTimeout, I>,
        Rem::Rest: Clean,
        M: Send,
    {
        let clear = self.effects.clear_timeout_at(slot);
        async move {
            clear.await;
            Session::new(self.effects)
        }
    }

    /// Drop a leading [`Repeat`](super::Repeat) on the current sequence.
    ///
    /// [`send`](Self::send) cannot skip a star by passing the following payload:
    /// `Repeat<Send<Role, T>>` unifies `T` with the repeated type, so a later
    /// `Send<Role, U>` is inferred as `T`. Call this after the last iteration,
    /// then send the suffix.
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// define_role_tag!(ToPeer);
    /// on_receive!(Idle, u8 => Send<ToPeer, String> => Done);
    /// fn bad<M>(s: Idle, eff: amaru_pure_stage::Effects<M>)
    /// where
    ///     M: amaru_pure_stage::SendData,
    /// {
    ///     let _ = s.receive(1u8, eff).discard_repeat();
    /// }
    /// ```
    pub fn discard_repeat(self) -> Session<M, Rem::Out>
    where
        Rem: super::DiscardRepeat,
    {
        Session::new(self.effects)
    }

    /// Protocol terminate. Consumes a [`Terminate`] allowance. Never returns.
    pub fn terminate<T, I>(self) -> impl Future<Output = T> + Send
    where
        Rem: Select<Terminate, I>,
        T: Send,
    {
        self.effects.terminate()
    }

    /// End the session when a remainder branch is [`To<S>`].
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// define_role_tag!(ToPeer);
    /// on_receive!(Idle, u8 => Send<ToPeer, String> => Done);
    /// fn bad<M>(s: Idle, eff: amaru_pure_stage::Effects<M>) -> Done {
    ///     s.receive(1u8, eff).finish()
    /// }
    /// ```
    ///
    /// A leading [`Repeat`](super::Repeat) does not block finish; a required
    /// effect sequenced after it still does:
    ///
    /// ```compile_fail
    /// use amaru_pure_stage::typestate::prelude::*;
    /// make_states!(Live { Idle; Done });
    /// define_role_tag!(ToPeer);
    /// on_receive!(Idle, u8 => Repeat<SendAny<ToPeer>>, Send<ToPeer, String> => Done);
    /// fn bad<M>(s: Idle, eff: amaru_pure_stage::Effects<M>) -> Done {
    ///     s.receive(1u8, eff).finish()
    /// }
    /// ```
    pub fn finish<S: State, I>(self) -> S
    where
        Rem: CanFinish<S, I>,
    {
        let _ = self;
        S::make(Marker(Private))
    }
}

impl<M, Rem: FmtPar> fmt::Debug for Session<M, Rem> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Session").field("remaining", &list::describe::<Rem>()).finish_non_exhaustive()
    }
}

type After<Rem, E, I> = <<Rem as Select<E, I>>::Rest as Clean>::Out;

/// Describe `State + Receive<In> → remainder` without constructing values.
#[cfg(test)]
pub(crate) fn describe_receive<S, In>() -> String
where
    S: OnReceive<In>,
    S::Then: FmtPar,
{
    format!("{} + Receive<{}> → {}", S::NAME, std::any::type_name::<In>(), list::describe::<S::Then>())
}
