global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: amaru-span-metrics
    static_configs:
    - targets: ['jaeger:8889']

  - job_name: amaru-metrics
    static_configs:
    - targets: ['otlp-collector:8889']
