[package]
name = "amaru-observability"
version = "0.1.2"
edition.workspace = true
description = "Observability instrumentation and structured event tracking for the Amaru Cardano node"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
amaru-kernel.workspace = true
amaru-observability-macros.workspace = true
cbor-data.workspace = true
cbor4ii.workspace = true
hex.workspace = true
inventory.workspace = true
opentelemetry.workspace = true
quote.workspace = true
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
syn.workspace = true
thiserror.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
opentelemetry_sdk = { workspace = true, features = ["logs", "testing", "trace"] }

[lints]
workspace = true
