lints.workspace = true

[package]
name = "amaru-ouroboros-traits"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[features]
default = []
test-utils = ["proptest", "dep:rand"]

[dependencies]
anyhow.workspace = true
hex.workspace = true
proptest = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

amaru-kernel.workspace = true
amaru-slot-arithmetic.workspace = true

[dev-dependencies]
proptest.workspace = true
