lints.workspace = true

[package]
name = "amaru-ouroboros-traits"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
amaru-kernel.workspace = true
amaru-slot-arithmetic.workspace = true
serde.workspace = true
