// Copyright 2025 PRAGMA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Random trees of `Header`s used to generate simulation walks.

use amaru_kernel::{Bytes, Header, HeaderHash, IsHeader, make_header, size::HEADER};
use proptest::prelude::Strategy;
use rand::{Rng, RngCore, SeedableRng, prelude::StdRng};

use super::tree::Tree;

/// Return a `proptest` Strategy producing a random `GeneratedTree` of a given depth.
pub fn any_headers_tree(depth: usize) -> impl Strategy<Value = Tree<Header>> {
    any_tree_of_headers(depth).prop_map(|generated_tree| generated_tree.tree)
}

/// Return a `proptest` Strategy producing a random `GeneratedTree` of a given depth.
pub fn any_tree_of_headers(depth: usize) -> impl Strategy<Value = GeneratedTree> {
    (0..u64::MAX).prop_map(move |seed| generate_tree_of_headers(seed, depth))
}

/// A generated tree of `Header`s.
/// The depth that was used to generate the tree can be accessed.
///
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTree {
    tree: Tree<Header>,
    depth: usize,
}

impl GeneratedTree {
    pub fn tree(&self) -> &Tree<Header> {
        &self.tree
    }

    pub fn best_chains(&self) -> Vec<Vec<Header>> {
        self.tree.branches()
    }

    pub fn depth(&self) -> usize {
        self.depth
    }

    pub fn nodes(&self) -> Vec<Header> {
        self.tree.nodes()
    }

    pub fn fork_nodes(&self) -> Vec<Header> {
        self.tree.fork_nodes()
    }

    pub fn leaves(&self) -> Vec<Header> {
        self.tree.leaves()
    }

    pub fn as_json(&self) -> serde_json::Value {
        self.tree.as_json()
    }
}

/// Generate a tree of headers of a given depth.
/// A seed is used to control the random generation of subtrees on top of a spine of length `depth`.
pub fn generate_tree_of_headers(seed: u64, depth: usize) -> GeneratedTree {
    let mut rng = StdRng::seed_from_u64(seed);

    let root = generate_header(1, 1, None, &mut rng);
    let mut root_tree = Tree::make_leaf(&root);
    let mut spine = generate_header_subtree(&mut rng, &mut root_tree, depth, depth - 1);
    spine.insert(0, root);
    GeneratedTree { tree: root_tree, depth }
}

/// Return only the generated tree of headers of a given depth.
pub fn generate_headers_tree(seed: u64, depth: usize) -> Tree<Header> {
    generate_tree_of_headers(seed, depth).tree
}

/// Given a random generator and a tree:
///
///  - Generate a spine (a chain of `TestHeaders`).
///  - Add subtrees to nodes of that spine.
///  - Graft the spine on the last child of `tree`.
///
/// We currently generate branches at every 1/3rd level of the spine and
/// randomly generate an additional branch at the same forking point
///
/// Slots are assigned to headers according to their depth so that 2 different forks would produce
/// headers at the same slot.
///
fn generate_header_subtree(
    rng: &mut StdRng,
    tree: &mut Tree<Header>,
    total_depth: usize,
    current_branch_expected_depth: usize,
) -> Vec<Header> {
    let header_body = tree.value.body().clone();
    let mut spine = generate_headers(
        current_branch_expected_depth,
        header_body.block_number,
        tree.value.slot().as_u64(),
        Some(tree.value.hash()),
        rng,
    );
    let mut current = tree;
    let mut current_size = 0;

    for child in spine.iter_mut() {
        current.add_child(child);
        current = current.get_last_child_mut().unwrap();
        current_size += 1;

        // We decide to branch at 1/3rd and 2/3rds of the total depth
        let must_branch = if total_depth >= 3 { current_size % (total_depth / 3) == 0 } else { false };
        if must_branch {
            let min_subtree_size = (current_branch_expected_depth - current_size) / 2;
            let max_subtree_size = current_branch_expected_depth - current_size;
            let subtree_size = rng.random_range(min_subtree_size..=max_subtree_size);
            generate_header_subtree(rng, current, total_depth, subtree_size);
            if rng.random_bool(0.2) {
                let subtree_size = rng.random_range(min_subtree_size..=max_subtree_size);
                generate_header_subtree(rng, current, total_depth, subtree_size);
            }
        }
    }
    spine
}

/// Generate a chain of headers.
///
/// The chain is generated by creating headers with random body hash, and linking
/// them to the previous header in the chain until the desired length is reached.
pub fn generate_headers_chain(length: usize) -> Vec<Header> {
    let mut rng = StdRng::seed_from_u64(42);
    generate_headers(length, 1, 1, None, &mut rng)
}

/// Generate just one header
pub fn generate_single_header() -> Header {
    generate_headers_chain(1)[0].clone()
}

// IMPLEMENTATION

/// Generate a chain of headers anchored at a given header.
///
/// The chain is generated by creating headers with random body hash, and linking
/// them to the previous header in the chain until the desired length is reached.
fn generate_headers(
    length: usize,
    start_block: u64,
    start_slot: u64,
    parent: Option<HeaderHash>,
    rng: &mut StdRng,
) -> Vec<Header> {
    let mut headers: Vec<Header> = Vec::new();
    let mut current_parent = parent;
    for i in 1..length + 1 {
        let slot = start_slot + i as u64;
        let block_number = start_block + i as u64;
        let header = generate_header(block_number, slot, current_parent, rng);
        current_parent = Some(header.hash());
        headers.push(header.clone());
    }
    headers
}

/// Generate a single `Header` but using the provided random generator.
fn generate_header(block: u64, slot: u64, parent: Option<HeaderHash>, rng: &mut StdRng) -> Header {
    // introduce some randomness in the header so that the hash is not predictable
    Header::new(make_header(block, slot, parent).body().clone(), Bytes::from(random_bytes_with_rng(HEADER, rng)))
}

/// Very simple function to generate random sequence of bytes of given length.
fn random_bytes_with_rng(arg: usize, rng: &mut StdRng) -> Vec<u8> {
    let mut buffer = vec![0; arg];
    rng.fill_bytes(&mut buffer);
    buffer
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_headers_tree() {
        let tree = generate_tree_of_headers(42, 5).tree;
        assert_eq!(tree.depth(), 5);
        check_nodes(&tree);
    }

    // HELPERS
    fn check_nodes(node: &Tree<Header>) {
        for child in &node.children {
            assert_eq!(child.value.parent(), Some(node.value.hash()));
            check_nodes(child);
        }
    }
}
