lints.workspace = true

[package]
name = "amaru-ledger"
version = "0.1.2"
edition.workspace = true
description = "Ledger engine for the Amaru Cardano node"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
build = "build.rs"

[features]
default = []
test-utils = ["proptest", "amaru-kernel/test-utils"]

[[bench]]
name = "volatile_db"
path = "benches/state/volatile_db/main.rs"
harness = false
required-features = ["test-utils"]

[dependencies]
# External dependencies ───────────────────────────────────────────────────────┐
anyhow.workspace = true
hex.workspace = true
itertools.workspace = true
num.workspace = true
proptest = { workspace = true, optional = true }
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

# Internal dependencies ───────────────────────────────────────────────────────┐
amaru-iter-borrow.workspace = true
amaru-kernel.workspace = true
amaru-metrics.workspace = true
amaru-observability.workspace = true
amaru-ouroboros-traits.workspace = true
amaru-plutus.workspace = true
amaru-progress-bar.workspace = true
amaru-uplc.workspace = true

[target.'cfg(all(not(target_family="wasm"), not(target_arch="riscv32")))'.dependencies]
amaru-deps.workspace = true

[dev-dependencies]
# External dependencies ───────────────────────────────────────────────────────┐
divan.workspace = true
proptest.workspace = true
rand.workspace = true
sysinfo.workspace = true
test-case.workspace = true
tempfile.workspace = true
toml.workspace = true

# Internal dependencies ───────────────────────────────────────────────────────┐
amaru-kernel = { workspace = true, features = ["test-utils"] }

[build-dependencies]
anyhow.workspace = true
serde_json = { workspace = true, features = ["std"] }
toml.workspace = true

[target.'cfg(not(std))'.dependencies]
num = { workspace = true, default-features = false, features = [
  "alloc",
  "libm",
] }

[package.metadata.cargo-machete]
ignored = ["amaru-deps"]
