// Copyright 2025 PRAGMA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub mod phase_one;
pub mod phase_two;

#[cfg(test)]
mod fixture;

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use amaru_kernel::{EraHistory, ProtocolParameters, Transaction, cbor, json, utils::serde::FilesystemRefResolver};
    use amaru_plutus::arena_pool::ArenaPool;

    use super::fixture::{Expected, Fixture, Predicate};
    use crate::{context::DefaultValidationContext, rules::block::validate_transaction};

    // One test case per fixture under tests/data/transaction/scenarios, generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/transaction_test_cases.rs"));

    fn run_conformance(fixture_path: &str) {
        let fixtures_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/transaction");

        let raw = fs::read_to_string(fixtures_dir.join(format!("{}.json", fixture_path)))
            .unwrap_or_else(|e| panic!("cannot read fixture {fixture_path}: {e}"));
        let fixture: Fixture =
            json::from_str(&raw).unwrap_or_else(|e| panic!("invalid json fixture {fixture_path}: {e}"));

        let decoded = cbor::decode::<Transaction>(&fixture.transaction);

        if matches!(fixture.expected, Expected::DecodingFailure) {
            assert!(
                decoded.is_err(),
                "expected the transaction to fail to be decoded, but it was successfully decoded"
            );
            return;
        }

        let tx: Transaction = decoded.expect("decode tx");

        let resolver = FilesystemRefResolver::new(fixtures_dir);
        let era_history: EraHistory = fixture.era_history.resolve_into(&resolver).expect("resolve eraHistory");
        let protocol_parameters: ProtocolParameters =
            fixture.protocol_parameters.resolve(&resolver).expect("resolve protocolParameters");

        let mut ctx = DefaultValidationContext::new(
            fixture.initial_state.utxo,
            fixture.initial_state.pools,
            fixture.initial_state.vrf_keys,
            fixture.initial_state.accounts,
            fixture.initial_state.dreps,
            fixture.initial_state.committee,
            fixture.initial_state.proposals,
            fixture.initial_state.proposals_roots,
            fixture.initial_state.pots.treasury,
            protocol_parameters.protocol_version,
        );

        let arena_pool = ArenaPool::new(1, 1_024_000);

        let result = validate_transaction(
            &mut ctx,
            &arena_pool,
            fixture.network,
            &protocol_parameters,
            &era_history,
            fixture.network.as_global_parameters().expect("missing global parameters for network"),
            fixture.initial_state.governance_activity,
            fixture.initial_state.guardrail_script,
            fixture.point,
            tx.tx_ref(),
        )
        .map_err(Predicate::from);

        match (fixture.expected, result) {
            (Expected::Pass, Ok(_)) => (),
            (Expected::Pass, Err(actual)) => panic!("expected pass, got error: {actual:?}"),
            (Expected::Fail(expected), Err(actual)) => {
                assert_eq!(actual, expected, "expected {expected:?}, got {actual:?}");
            }
            (Expected::Fail(expected), Ok(_)) => panic!("expected fail ({expected:?}), got pass"),
            (Expected::DecodingFailure, _) => unreachable!("handled before decoding the transaction"),
        }
    }
}
