#!/usr/bin/env bash

set -euo pipefail

exitWithUsage () {
  echo -e "\033[1;31mError: missing argument(s)!\033[00m\n"
  echo -e "\033[1;32mUsage:\033[00m\n    $0 BUILD_PROFILE TARGET_EPOCH\n"
  echo -e "\033[1mExamples:\033[00m \n    $0 release 127.0.0.1:3000 0.0.0.0:0    173\n    $0 debug 127.0.0.1:3001 0.0.0.0:8000 200 preprod"
  exit 1
}

if [ $# -lt 4 ] || [ $# -gt 5 ]; then
    exitWithUsage
fi

BUILD_PROFILE=$1
if [ -z "$BUILD_PROFILE" ]; then
  exitWithUsage
fi

TARGET_EPOCH=$2
if [ -z "$TARGET_EPOCH" ]; then
  exitWithUsage
fi

echo -e "      \033[1;32mTarget\033[00m epoch $TARGET_EPOCH"

AMARU_TRACE="amaru=info" cargo run --profile $BUILD_PROFILE -- --with-json-traces daemon | while read line; do
  echo "$line"
  EVENT=$(jq -r '.fields.message' <<< "$line" 2>/dev/null)
  SPAN=$(jq -r '.span.name' <<< "$line" 2>/dev/null)
  if [ "$EVENT" = "exit" ] && [ "$SPAN" = "epoch_transition" ]; then
    EPOCH=$(jq -r '.span.into' <<< "$line" 2>/dev/null)
    if [ "$EPOCH" -eq "$TARGET_EPOCH" ]; then
      echo "Target epoch reached, stopping the process."
      pkill -INT -P $$
      break
    fi
  fi
done
