#!/usr/bin/env bash

set -u

exitWithUsage () {
  echo -e "\033[1;31mError: missing argument(s)!\033[00m\n"
  echo -e "\033[1;32mUsage:\033[00m\n    $0 BUILD_PROFILE TARGET_EPOCH\n"
  echo -e "\033[1mExamples:\033[00m \n    $0 release 173"
  exit 1
}

if [ $# != 2 ]; then
    exitWithUsage
fi

BUILD_PROFILE=$1
if [ -z "$BUILD_PROFILE" ]; then
  exitWithUsage
fi

TARGET_EPOCH=$2
if [ -z "$TARGET_EPOCH" ]; then
  exitWithUsage
fi

echo -e "      \033[1;32mTarget\033[00m epoch $TARGET_EPOCH"
cargo build --profile $BUILD_PROFILE --bin amaru

if [ -n "${AMARU_TRACE:-}" ]; then
  export AMARU_TRACE
fi

function run() {
  /bin/sh -c "echo exitPID=\$\$; exec cargo run --profile $BUILD_PROFILE -- --with-json-traces run"
}

ENDED=false
while read -r line; do
  if [ "${line:0:8}" = "exitPID=" ]; then
    PID="${line:8}"
    echo "PID=$PID (me=$$)"
  fi
  EVENT=$(jq -r '.fields.message' <<< "$line" 2>/dev/null)
  SPAN=$(jq -r '.span.name' <<< "$line" 2>/dev/null)
  if [ "$EVENT" = "exit" ] && [ "$SPAN" = "epoch_transition" ]; then
    EPOCH=$(jq -r '.span.into' <<< "$line" 2>/dev/null)
    echo "Epoch $EPOCH"
    if [ "$EPOCH" -eq "$TARGET_EPOCH" ]; then
      echo "Target epoch reached, stopping the process."
      kill -INT "$PID"
      ENDED=true
      break
    fi
  fi
done < <(run | tee /dev/stderr | grep --line-buffered "exit")

# return value needs to reflect whether target epoch was reached
echo "ENDED=$ENDED"
test "$ENDED" = true
