[package]
name = "host"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

publish = false

[dependencies]
methods = { path = "methods" }
risc0-zkvm = { version = "1.2.4" }
amaru-examples-shared = { path = "../shared" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }