lints.workspace = true

[package]
name = "amaru-network"
version = "0.1.2"
edition.workspace = true
description = "Network layer and protocol handling for the Amaru Cardano node"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bytes = { workspace = true, features = ["serde"] }
pallas-network.workspace = true
parking_lot.workspace = true
socket2.workspace = true
tokio = { workspace = true, features = ["net"] }
tracing.workspace = true

amaru-kernel.workspace = true
amaru-observability.workspace = true
amaru-ouroboros.workspace = true
amaru-pure-stage.workspace = true

[target.'cfg(all(not(target_family="wasm"), not(target_arch="riscv32")))'.dependencies]
amaru-deps.workspace = true

[dev-dependencies]
anyhow.workspace = true
amaru-mempool.workspace = true
hex.workspace = true
proptest.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber.workspace = true

[package.metadata.cargo-machete]
ignored = ["amaru-deps"]
