lints.workspace = true

[package]
name = "amaru-node"
version = "0.1.0"
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "../../README.md"
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
build = "build/build.rs"
include = ["src/**/*", "config/**", "Cargo.toml", "build.rs"]

[features]
test-utils = ["tracing-subscriber"]

[build-dependencies]
amaru-kernel.workspace = true
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
ureq.workspace = true

[dependencies]
# External dependencies ───────────────────────────────────────────────────────┐
anyhow.workspace = true
axum.workspace = true
futures-util.workspace = true
hex.workspace = true
minicbor.workspace = true
num.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["std"] }
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
  "fs",
  "net",
  "rt",
  "rt-multi-thread",
] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }

# Internal dependencies ───────────────────────────────────────────────────────┐
amaru-consensus.workspace = true
amaru-kernel = { workspace = true, features = ["tracing", "clap"] }
amaru-ledger.workspace = true
amaru-mempool.workspace = true
amaru-metrics.workspace = true
amaru-network.workspace = true
amaru-observability.workspace = true
amaru-ouroboros.workspace = true
amaru-plutus.workspace = true
amaru-protocols.workspace = true
amaru-pure-stage.workspace = true
amaru-stores.workspace = true

[target.'cfg(all(not(target_family="wasm"), not(target_arch="riscv32")))'.dependencies]
amaru-deps.workspace = true

[dev-dependencies]
# External dependencies ───────────────────────────────────────────────────────┐
assert_cmd.workspace = true
diff_json.workspace = true
quote.workspace = true
rocksdb.workspace = true
syn.workspace = true
tempfile.workspace = true
test-case.workspace = true
tracing-subscriber.workspace = true
xz.workspace = true

# Internal dependencies ───────────────────────────────────────────────────────┐
amaru-consensus = { workspace = true, features = ["test-utils"] }
amaru-iter-borrow.workspace = true
amaru-kernel = { workspace = true, features = ["test-utils"] }
amaru-ledger = { workspace = true, features = ["test-utils"] }
amaru-ouroboros-traits = { workspace = true, features = ["test-utils"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["-D", "warnings"]

[package.metadata.cargo-machete]
ignored = ["amaru-deps"]
