name: Coding Practices

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft, ready_for_review]
    branches: ["*"]

jobs:
  rust-toolchain:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: ./scripts/check-rust-toolchain-version

  changes:
    runs-on: ubuntu-24.04
    # Required to expose outputs to dependent jobs (unused-dependencies, licenses-compatibility)
    outputs:
      dependencies: ${{ steps.changes.outputs.dependencies }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            dependencies:
              - "Cargo.toml"
              - "Cargo.lock"
              - "crates/**/Cargo.toml"
              - "crates/**/Cargo.lock"

  unused-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: bnjbvr/cargo-machete
          tag: v0.7.0
          binaries-location: cargo-machete-v0.7.0-x86_64-unknown-linux-musl
      - run: cargo-machete

  licenses-compatibility:
    needs: changes
    if: ${{ needs.changes.outputs.dependencies == 'true' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: EmbarkStudios/cargo-deny
          tag: 0.16.4
          binaries-location: cargo-deny-0.16.4-x86_64-unknown-linux-musl
      - run: cargo deny-amaru

  license-headers:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: viperproject/check-license-header@v2
        with:
          path: .
          config: .github/check-license-header.config.json
          strict: false

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cache
      - run: cargo clippy-amaru

  formatting:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt-amaru

  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/cache
      - name: Check documentation
        run: |
          export RUSTDOCFLAGS="-D warnings"
          cargo doc --no-deps --workspace
          cargo doc -p amaru --no-deps --all-features
