name: Nightly Sync

on:
  schedule:
    - cron: '00 08,22 * * *'
  workflow_dispatch:
    inputs:
      synchronization-level:
        description: 'Desired % synchronization level. Between 0 and 1.'
        required: false
        default: 1
        type: number

jobs:
  sync_and_cache:
    strategy:
      matrix:
        network: [ preprod, preview ]
        ogmios_version: [ v6.11.2 ]
        cardano_node_version: [ 10.1.4 ]

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - id: timestamp
      shell: bash
      run: |
        echo "value=$(/bin/date -u '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - id: cache
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/db-${{ matrix.network }}
        key: cardano-node-ogmios-${{ matrix.network }}-${{ steps.timestamp.outputs.value }}
        restore-keys: |
          cardano-node-ogmios-${{ matrix.network }}

    - uses: CardanoSolutions/gh-action-cardano-node-ogmios-docker-sync@v1.2.2
      with:
        db-dir: ${{ runner.temp }}/db-${{ matrix.network }}
        network: ${{ matrix.network }}
        version: ${{ matrix.ogmios_version }}_${{ matrix.cardano_node_version }}
        synchronization-level: ${{ inputs.synchronization-level || 1 }}

    # Remove old immutable chunks from the database, we don't need them and they make cache & on-disk system larger.
    - name: prune node db
      if: steps.cache.outputs.cache-hit == 'false'
      shell: bash
      working-directory: ${{ runner.temp }}/db-${{ matrix.network }}
      run: |
        if [ "$NETWORK" == "preprod" ]; then
          rm -f immutable/00*.chunk immutable/01*.chunk immutable/02*.chunk immutable/030*.chunk
        fi

        if [ "$NETWORK" == "preview" ]; then
          rm -f immutable/0*.chunk immutable/10*.chunk immutable/11*.chunk
        fi
      env:
        NETWORK: ${{ matrix.network }}
